---
  dependencies:
    - role: geerlingguy.mac.mas
      vars:
        mas_installed_apps:
          - id: 462054704
            name: Microsoft Word
          - id: 462058435
            name: Microsoft Excel
          - id: 784801555
            name: Microsoft OneNote
          - id: 823766827
            name: Microsoft OneDrive
          - id: 985367838
            name: Microsoft Outlook
          - id: 462062816
            name: Microsoft PowerPoint
        mas_uninstalled_apps:
          - { id: 408981434, name: "iMovie" }
          - { id: 409183694, name: "Keynote" }
          - { id: 409201541, name: "Pages" }
          - { id: 409203825, name: "Numbers" }
          - { id: 682658836, name: "GarageBand" }
    - role: geerlingguy.mac.dock
      vars:
        dockitems_remove:
          - Launchpad
          - TV
          - Podcasts
          - 'App Store'
          - Messages
          - Safari